Mongodb:
  useMongodb: true
  host: "localhost"
  port: 27017
  collection: "PlusLib"
  username: ""
  password: ""


VoiceChat:
  useVoiceChat: false
  keepAudioLoaded: true # If true, the audio will be loaded into memory. If false, the audio will be streamed from the server.